<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.1.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Untitled 69 Form verzenden',
	'heading' => 'Nieuw formulier verzenden',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Ingeschakeld',
		'checkbox_unchecked' => 'Uitgeschakeld',
		'submitted_from' => 'Formulier verzonden op website: %s',
		'submitted_by' => 'IP-adres van bezoeker: %s',
		'too_many_submissions' => 'Te veel recente inzendingen van dit IP',
		'failed_to_send_email' => 'Verzenden van e-mail is mislukt',
		'invalid_reCAPTCHA_private_key' => 'Ongeldige reCAPTCHA-privécode.',
		'invalid_reCAPTCHA2_private_key' => 'Ongeldige persoonlijke reCAPTCHA 2.0-code.',
		'invalid_reCAPTCHA2_server_response' => 'Ongeldige reCAPTCHA 2.0-serverreactie.',
		'invalid_field_type' => 'Onbekend veldtype %s.',
		'invalid_form_config' => 'Het veld %s heeft een ongeldige configuratie.',
		'unknown_method' => 'Onbekende serveraanvraagmethode'
	),
	'email' => array(
		'from' => 'a.vasic777@gmail.com',
		'to' => 'a.vasic777@gmail.com'
	),
	'fields' => array(
		'custom_U257017' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Naam',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Naam is vereist.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'E-mailadres',
			'required' => true,
			'errors' => array(
				'required' => 'Veld E-mailadres is vereist.',
				'format' => 'Veld E-mailadres bevat een ongeldig e-mailadres.'
			)
		),
		'custom_U256999' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Bedrijf',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Bedrijf is vereist.'
			)
		),
		'custom_U256995' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Zakelijk adres',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Zakelijk adres is vereist.'
			)
		),
		'custom_U257021' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Plaats',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Plaats is vereist.'
			)
		),
		'custom_U257003' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Staat/land',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Staat/land is vereist.'
			)
		),
		'custom_U257012' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Postcode',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Postcode is vereist.'
			)
		),
		'custom_U257008' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Land',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Land is vereist.'
			)
		),
		'custom_U257025' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Bericht',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Bericht is vereist.'
			)
		),
		'custom_U257116' => array(
			'order' => 10,
			'type' => 'checkbox',
			'label' => 'Label selectievakje',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Label selectievakje is vereist.'
			)
		),
		'custom_U257160' => array(
			'order' => 11,
			'type' => 'radiogroup',
			'label' => 'Groep keuzerondjes',
			'required' => true,
			'optionItems' => array(
				'Label keuzerondjes',
				'Label keuzerondjes'
			),
			'errors' => array(
				'required' => 'Veld Groep keuzerondjes is vereist.',
				'format' => 'Het veld Groep keuzerondjes heeft een ongeldige waarde.'
			)
		)
	)
);

process_form($form);
?>
