<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.1.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Aanmeld formulier KROS RTS  Form verzenden',
	'heading' => 'Nieuw formulier verzenden',
	'success_redirect' => 'bevestiging-aanmelding.html',
	'resources' => array(
		'checkbox_checked' => 'Ingeschakeld',
		'checkbox_unchecked' => 'Uitgeschakeld',
		'submitted_from' => 'Formulier verzonden op website: %s',
		'submitted_by' => 'IP-adres van bezoeker: %s',
		'too_many_submissions' => 'Te veel recente inzendingen van dit IP',
		'failed_to_send_email' => 'Verzenden van e-mail is mislukt',
		'invalid_reCAPTCHA_private_key' => 'Ongeldige reCAPTCHA-privécode.',
		'invalid_reCAPTCHA2_private_key' => 'Ongeldige persoonlijke reCAPTCHA 2.0-code.',
		'invalid_reCAPTCHA2_server_response' => 'Ongeldige reCAPTCHA 2.0-serverreactie.',
		'invalid_field_type' => 'Onbekend veldtype %s.',
		'invalid_form_config' => 'Het veld %s heeft een ongeldige configuratie.',
		'unknown_method' => 'Onbekende serveraanvraagmethode'
	),
	'email' => array(
		'from' => 'rtskros@soprotterdam.com',
		'to' => 'rtskros@soprotterdam.com'
	),
	'fields' => array(
		'custom_U258446' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Naam en achternaam ouder',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Naam en achternaam ouder is vereist.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'E-mailadres',
			'required' => true,
			'errors' => array(
				'required' => 'Veld E-mailadres is vereist.',
				'format' => 'Veld E-mailadres bevat een ongeldig e-mailadres.'
			)
		),
		'custom_U258428' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Naam kind 1',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Naam kind 1 is vereist.'
			)
		),
		'custom_U258424' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Naam kind 2',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U258450' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Naam kind 3',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U258441' => array(
			'order' => 12,
			'type' => 'string',
			'label' => 'Telefoon',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Telefoon is vereist.'
			)
		),
		'custom_U258437' => array(
			'order' => 13,
			'type' => 'string',
			'label' => 'Stad',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Stad is vereist.'
			)
		),
		'custom_U258454' => array(
			'order' => 14,
			'type' => 'string',
			'label' => 'Bericht',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U259446' => array(
			'order' => 10,
			'type' => 'string',
			'label' => 'Leeftijd kind 3',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U259563' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Leeftijd kind 2',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U259575' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Leeftijd kind 1',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Leeftijd kind 1 is vereist.'
			)
		),
		'custom_U261877' => array(
			'order' => 15,
			'type' => 'checkbox',
			'label' => 'Met deze aanmelding bevestig ik dat ik 10 euro\'s betaald heb voor de deelname aan KROS RTS en dat ik eens ben dat het bedrag in zijn geheel gedoneerd wordt aan Atletiek Club Prilužje uit Kosovo en Metohija. 
Het bedrag van 10 euro kunt u overmaken op de',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Met deze aanmelding bevestig ik dat ik 10 euro\'s betaald heb voor de deelname aan KROS RTS en dat ik eens ben dat het bedrag in zijn geheel gedoneerd wordt aan Atletiek Club Prilužje uit Kosovo en Metohija. 
Het bedrag van 10 euro kunt u overmaken op de is vereist.'
			)
		),
		'custom_U262135' => array(
			'order' => 5,
			'type' => 'radiogroup',
			'label' => 'Maat T-shirt Kind 1',
			'required' => true,
			'optionItems' => array(
				'104',
				'110',
				'116',
				'122',
				'128',
				'134',
				'140',
				'146',
				'152',
				'158',
				'164',
				'S',
				'M',
				'L',
				'XL'
			),
			'errors' => array(
				'required' => 'Veld Maat T-shirt Kind 1 is vereist.',
				'format' => 'Het veld Maat T-shirt Kind 1 heeft een ongeldige waarde.'
			)
		),
		'custom_U262530' => array(
			'order' => 8,
			'type' => 'radiogroup',
			'label' => 'Maat T-shirt Kind 2',
			'required' => false,
			'optionItems' => array(
				'104',
				'110',
				'116',
				'122',
				'128',
				'134',
				'140',
				'146',
				'152',
				'158',
				'164',
				'S',
				'M',
				'L',
				'XL'
			),
			'errors' => array(
				'format' => 'Het veld Maat T-shirt Kind 2 heeft een ongeldige waarde.'
			)
		),
		'custom_U262764' => array(
			'order' => 11,
			'type' => 'radiogroup',
			'label' => 'Groep keuzerondjes',
			'required' => false,
			'optionItems' => array(
				'104',
				'110',
				'116',
				'122',
				'128',
				'134',
				'140',
				'146',
				'152',
				'158',
				'164',
				'S',
				'M',
				'L',
				'XL'
			),
			'errors' => array(
				'format' => 'Het veld Groep keuzerondjes heeft een ongeldige waarde.'
			)
		)
	)
);

process_form($form);
?>
