<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.1.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Aanmelding sportdag Form verzenden',
	'heading' => 'Nieuw formulier verzenden',
	'success_redirect' => 'betaling.html',
	'resources' => array(
		'checkbox_checked' => 'Ingeschakeld',
		'checkbox_unchecked' => 'Uitgeschakeld',
		'submitted_from' => 'Formulier verzonden op website: %s',
		'submitted_by' => 'IP-adres van bezoeker: %s',
		'too_many_submissions' => 'Te veel recente inzendingen van dit IP',
		'failed_to_send_email' => 'Verzenden van e-mail is mislukt',
		'invalid_reCAPTCHA_private_key' => 'Ongeldige reCAPTCHA-privécode.',
		'invalid_reCAPTCHA2_private_key' => 'Ongeldige persoonlijke reCAPTCHA 2.0-code.',
		'invalid_reCAPTCHA2_server_response' => 'Ongeldige reCAPTCHA 2.0-serverreactie.',
		'invalid_field_type' => 'Onbekend veldtype %s.',
		'invalid_form_config' => 'Het veld %s heeft een ongeldige configuratie.',
		'unknown_method' => 'Onbekende serveraanvraagmethode'
	),
	'email' => array(
		'from' => 'waterpoloclinic@soprotterdam.com',
		'to' => 'waterpoloclinic@soprotterdam.com'
	),
	'fields' => array(
		'custom_U83916' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Naam ouder',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Naam ouder is vereist.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Emailadres',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Emailadres is vereist.',
				'format' => 'Veld Emailadres bevat een ongeldig e-mailadres.'
			)
		),
		'custom_U83930' => array(
			'order' => 14,
			'type' => 'string',
			'label' => 'Bericht',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U83908' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'GSM-nummer',
			'required' => true,
			'errors' => array(
				'required' => 'Veld GSM-nummer is vereist.'
			)
		),
		'custom_U83890' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Telefoonnummer thuis',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U83926' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Huisadres',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Huisadres is vereist.'
			)
		),
		'custom_U83894' => array(
			'order' => 10,
			'type' => 'string',
			'label' => 'Stad',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Stad is vereist.'
			)
		),
		'custom_U83912' => array(
			'order' => 11,
			'type' => 'string',
			'label' => 'Postcode',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Postcode is vereist.'
			)
		),
		'custom_U83904' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Naam kind, leeftijd',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Naam kind, leeftijd is vereist.'
			)
		),
		'custom_U83934' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Naam kind, leeftijd',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U83899' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Naam kind, leeftijd',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U92099' => array(
			'order' => 12,
			'type' => 'checkbox',
			'label' => 'Groep 10-13 jaar',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U92174' => array(
			'order' => 13,
			'type' => 'checkbox',
			'label' => 'Groep 14-16 jaar',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U168468' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Geef hieronder de maat en het aantal gewenste T-shirts aan',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Geef hieronder de maat en het aantal gewenste T-shirts aan is vereist.'
			)
		)
	)
);

process_form($form);
?>
