<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.1.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Anketa Form verzenden',
	'heading' => 'Nieuw formulier verzenden',
	'success_redirect' => '%d1%85%d0%b2%d0%b0%d0%bb%d0%b0-%d0%bd%d0%b0.html',
	'resources' => array(
		'checkbox_checked' => 'Ingeschakeld',
		'checkbox_unchecked' => 'Uitgeschakeld',
		'submitted_from' => 'Formulier verzonden op website: %s',
		'submitted_by' => 'IP-adres van bezoeker: %s',
		'too_many_submissions' => 'Te veel recente inzendingen van dit IP',
		'failed_to_send_email' => 'Verzenden van e-mail is mislukt',
		'invalid_reCAPTCHA_private_key' => 'Ongeldige reCAPTCHA-privécode.',
		'invalid_reCAPTCHA2_private_key' => 'Ongeldige persoonlijke reCAPTCHA 2.0-code.',
		'invalid_reCAPTCHA2_server_response' => 'Ongeldige reCAPTCHA 2.0-serverreactie.',
		'invalid_field_type' => 'Onbekend veldtype %s.',
		'invalid_form_config' => 'Het veld %s heeft een ongeldige configuratie.',
		'unknown_method' => 'Onbekende serveraanvraagmethode'
	),
	'email' => array(
		'from' => 'anketa@soprotterdam.com',
		'to' => 'anketa@soprotterdam.com'
	),
	'fields' => array(
		'custom_U253283' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Име и презиме',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Име и презиме is vereist.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Емаил адреса',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Емаил адреса is vereist.',
				'format' => 'Veld Емаил адреса bevat een ongeldig e-mailadres.'
			)
		),
		'custom_U253263' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Град Становања',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Град Становања is vereist.'
			)
		),
		'custom_U253291' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Колило деце имате која су заинтересована за похађање српске школе?',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Колило деце имате која су заинтересована за похађање српске школе? is vereist.'
			)
		),
		'custom_U253267' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Узраст деце

Дете 1',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Узраст деце

Дете 1 is vereist.'
			)
		),
		'custom_U253259' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Дете 2',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Дете 2 is vereist.'
			)
		),
		'custom_U253275' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Дете 3',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Дете 3 is vereist.'
			)
		),
		'custom_U253279' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Порука',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Порука is vereist.'
			)
		),
		'custom_U253463' => array(
			'order' => 8,
			'type' => 'checkboxgroup',
			'label' => 'Дали сте заинтересовани да волонтирате у школи и другим активностима везани за школска дешавања?',
			'required' => true,
			'optionItems' => array(
				'Да',
				'Не'
			),
			'errors' => array(
				'required' => 'Veld Дали сте заинтересовани да волонтирате у школи и другим активностима везани за школска дешавања? is vereist.',
				'format' => 'Het veld Дали сте заинтересовани да волонтирате у школи и другим активностима везани за школска дешавања? heeft een ongeldige waarde.'
			)
		)
	)
);

process_form($form);
?>
