<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.1.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Prijava za atletiku Form verzenden',
	'heading' => 'Nieuw formulier verzenden',
	'success_redirect' => 'prijava-za-atletiku-poslata.html',
	'resources' => array(
		'checkbox_checked' => 'Ingeschakeld',
		'checkbox_unchecked' => 'Uitgeschakeld',
		'submitted_from' => 'Formulier verzonden op website: %s',
		'submitted_by' => 'IP-adres van bezoeker: %s',
		'too_many_submissions' => 'Te veel recente inzendingen van dit IP',
		'failed_to_send_email' => 'Verzenden van e-mail is mislukt',
		'invalid_reCAPTCHA_private_key' => 'Ongeldige reCAPTCHA-privécode.',
		'invalid_reCAPTCHA2_private_key' => 'Ongeldige persoonlijke reCAPTCHA 2.0-code.',
		'invalid_reCAPTCHA2_server_response' => 'Ongeldige reCAPTCHA 2.0-serverreactie.',
		'invalid_field_type' => 'Onbekend veldtype %s.',
		'invalid_form_config' => 'Het veld %s heeft een ongeldige configuratie.',
		'unknown_method' => 'Onbekende serveraanvraagmethode'
	),
	'email' => array(
		'from' => 'atletiek@soprotterdam.com',
		'to' => 'atletiek@soprotterdam.com'
	),
	'fields' => array(
		'custom_U179325' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Име родитеља',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Име родитеља is vereist.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Адреса е-поште',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Адреса е-поште is vereist.',
				'format' => 'Veld Адреса е-поште bevat een ongeldig e-mailadres.'
			)
		),
		'custom_U179316' => array(
			'order' => 14,
			'type' => 'string',
			'label' => 'Порука',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U179312' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Број мобилног телефона',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Број мобилног телефона is vereist.'
			)
		),
		'custom_U179321' => array(
			'order' => 10,
			'type' => 'string',
			'label' => 'Број телефона код куће',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U179308' => array(
			'order' => 11,
			'type' => 'string',
			'label' => 'Кућна адреса',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Кућна адреса is vereist.'
			)
		),
		'custom_U179291' => array(
			'order' => 12,
			'type' => 'string',
			'label' => 'Град',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Град is vereist.'
			)
		),
		'custom_U179295' => array(
			'order' => 13,
			'type' => 'string',
			'label' => 'Поштански број',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Поштански број is vereist.'
			)
		),
		'custom_U179282' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Име и презиме детета, годиште детета',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Име и презиме детета, годиште детета is vereist.'
			)
		),
		'custom_U179278' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Име и презиме детета, годиште детета',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U179299' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Име и презиме детета, годиште детета',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U179329' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Величина мајце',
			'required' => true,
			'errors' => array(
				'required' => 'Veld Величина мајце is vereist.'
			)
		),
		'custom_U179334' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Величина мајце',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U179286' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Величина мајце',
			'required' => false,
			'errors' => array(
			)
		)
	)
);

process_form($form);
?>
